# this is github project sentinel application.yml file
server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/prsentinel
    username: postgres
    password: postgres

#spring ai dependencies configuration
  ai:
    vectorstore:
      pgvector:
        index-type: HNSW
        distance-type: COSINE_DISTANCE
        dimensions: 768
    google:
      genai:
        api-key: ${GOOGLE_GENAI_API_KEY}
        chat:
          options:
            model: gemini-3.5-flash
        embedding:
          text:
            options:
              model: gemini-embedding-001

github:
  app:
    id: 4272698
    private-key-path: D:\springboot_learning\pr-sentinel-vid-pkcs8.pem

  webhook:
    secret: ${GITHUB_WEBHOOK_SECRET}