server:
  port: 8080

spring:
  ai:
    google:
      genai:
        api-key: ${GOOGLE_GENAI_API_KEY}
        chat:
          options:
            model: gemini-2.5-flash


github:
  app:
    id: 4272698
    private-key-path: D:\springboot_learning\pr-sentinel-vid-pkcs8.pem

  webhook:
    secret: ${GITHUB_WEBHOOK_SECRET}


